INSERT INTO PUBLIC.DIALOGS (DIALOG_ID, IMAGE, NAME) VALUES (1196, null, null);
INSERT INTO PUBLIC.DIALOGS (DIALOG_ID, IMAGE, NAME) VALUES (1202, 'https://localhost/img/default.jpg', 'Группа');
INSERT INTO PUBLIC.DIALOGS (DIALOG_ID, IMAGE, NAME) VALUES (1223, null, null);
INSERT INTO PUBLIC.DIALOGS (DIALOG_ID, IMAGE, NAME) VALUES (1224, null, null);
INSERT INTO PUBLIC.DIALOGS (DIALOG_ID, IMAGE, NAME) VALUES (1277, null, null);